2023-08-01 11:29:01,037 INFO    StreamThr :22572 [internal.py:wandb_internal():86] W&B internal server running at pid: 22572, started at: 2023-08-01 11:29:01.034159
2023-08-01 11:29:01,039 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status
2023-08-01 11:29:01,066 INFO    WriterThread:22572 [datastore.py:open_for_write():85] open: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\run-yma4yd7g.wandb
2023-08-01 11:29:01,067 DEBUG   SenderThread:22572 [sender.py:send():379] send: header
2023-08-01 11:29:01,068 DEBUG   SenderThread:22572 [sender.py:send():379] send: run
2023-08-01 11:29:02,321 INFO    SenderThread:22572 [dir_watcher.py:__init__():211] watching files in: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files
2023-08-01 11:29:02,323 INFO    SenderThread:22572 [sender.py:_start_run_threads():1122] run started: yma4yd7g with start time 1690871341.042672
2023-08-01 11:29:02,323 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: summary_record
2023-08-01 11:29:02,326 INFO    SenderThread:22572 [sender.py:_save_file():1376] saving file wandb-summary.json with policy end
2023-08-01 11:29:02,334 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: check_version
2023-08-01 11:29:02,334 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: check_version
2023-08-01 11:29:03,133 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: run_start
2023-08-01 11:29:03,199 DEBUG   HandlerThread:22572 [system_info.py:__init__():31] System info init
2023-08-01 11:29:03,200 DEBUG   HandlerThread:22572 [system_info.py:__init__():46] System info init done
2023-08-01 11:29:03,200 INFO    HandlerThread:22572 [system_monitor.py:start():181] Starting system monitor
2023-08-01 11:29:03,200 INFO    SystemMonitor:22572 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-08-01 11:29:03,201 INFO    HandlerThread:22572 [system_monitor.py:probe():201] Collecting system info
2023-08-01 11:29:03,211 INFO    SystemMonitor:22572 [interfaces.py:start():190] Started cpu monitoring
2023-08-01 11:29:03,212 INFO    SystemMonitor:22572 [interfaces.py:start():190] Started disk monitoring
2023-08-01 11:29:03,213 INFO    SystemMonitor:22572 [interfaces.py:start():190] Started gpu monitoring
2023-08-01 11:29:03,230 INFO    SystemMonitor:22572 [interfaces.py:start():190] Started memory monitoring
2023-08-01 11:29:03,240 DEBUG   HandlerThread:22572 [system_info.py:probe():195] Probing system
2023-08-01 11:29:03,252 INFO    SystemMonitor:22572 [interfaces.py:start():190] Started network monitoring
2023-08-01 11:29:03,263 DEBUG   HandlerThread:22572 [gitlib.py:_init_repo():53] git repository is invalid
2023-08-01 11:29:03,263 DEBUG   HandlerThread:22572 [system_info.py:probe():240] Probing system done
2023-08-01 11:29:03,264 DEBUG   HandlerThread:22572 [system_monitor.py:probe():210] {'os': 'Windows-10-10.0.22621-SP0', 'python': '3.9.16', 'heartbeatAt': '2023-08-01T06:29:03.240100', 'startedAt': '2023-08-01T06:29:00.993193', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'host': 'ahsan', 'username': 'Pc', 'executable': 'c:\\Users\\Pc\\miniconda3\\envs\\tf\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 12, 'cpu_freq': {'current': 2100.0, 'min': 0.0, 'max': 2100.0}, 'cpu_freq_per_core': [{'current': 2100.0, 'min': 0.0, 'max': 2100.0}], 'disk': {'total': 195.31151962280273, 'used': 185.70372009277344}, 'gpu': 'NVIDIA GeForce RTX 3050 6GB Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3050 6GB Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 7.64898681640625}}
2023-08-01 11:29:03,264 INFO    HandlerThread:22572 [system_monitor.py:probe():211] Finished collecting system info
2023-08-01 11:29:03,264 INFO    HandlerThread:22572 [system_monitor.py:probe():214] Publishing system info
2023-08-01 11:29:03,264 DEBUG   HandlerThread:22572 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-08-01 11:29:03,267 DEBUG   HandlerThread:22572 [system_info.py:_save_pip():67] Saving pip packages done
2023-08-01 11:29:03,269 DEBUG   HandlerThread:22572 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-08-01 11:29:03,331 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_created():272] file/dir created: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\conda-environment.yaml
2023-08-01 11:29:03,333 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_created():272] file/dir created: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\wandb-summary.json
2023-08-01 11:29:03,334 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_created():272] file/dir created: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\requirements.txt
2023-08-01 11:29:15,319 DEBUG   HandlerThread:22572 [system_info.py:_save_conda():86] Saving conda packages done
2023-08-01 11:29:15,320 INFO    HandlerThread:22572 [system_monitor.py:probe():216] Finished publishing system info
2023-08-01 11:29:15,379 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:15,379 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: keepalive
2023-08-01 11:29:15,380 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:15,380 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: keepalive
2023-08-01 11:29:15,382 DEBUG   SenderThread:22572 [sender.py:send():379] send: files
2023-08-01 11:29:15,383 INFO    SenderThread:22572 [sender.py:_save_file():1376] saving file wandb-metadata.json with policy now
2023-08-01 11:29:15,496 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: stop_status
2023-08-01 11:29:15,500 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: stop_status
2023-08-01 11:29:15,510 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_modified():289] file/dir modified: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\conda-environment.yaml
2023-08-01 11:29:15,512 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_created():272] file/dir created: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\wandb-metadata.json
2023-08-01 11:29:16,208 DEBUG   SenderThread:22572 [sender.py:send():379] send: telemetry
2023-08-01 11:29:16,210 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:16,226 DEBUG   SenderThread:22572 [sender.py:send():379] send: telemetry
2023-08-01 11:29:16,521 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_created():272] file/dir created: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\output.log
2023-08-01 11:29:16,660 DEBUG   SenderThread:22572 [sender.py:send():379] send: exit
2023-08-01 11:29:16,660 INFO    SenderThread:22572 [sender.py:send_exit():584] handling exit code: 1
2023-08-01 11:29:16,661 INFO    SenderThread:22572 [sender.py:send_exit():586] handling runtime: 13
2023-08-01 11:29:16,662 INFO    SenderThread:22572 [sender.py:_save_file():1376] saving file wandb-summary.json with policy end
2023-08-01 11:29:16,663 INFO    SenderThread:22572 [sender.py:send_exit():592] send defer
2023-08-01 11:29:16,664 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,665 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 0
2023-08-01 11:29:16,665 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,665 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 0
2023-08-01 11:29:16,665 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 1
2023-08-01 11:29:16,665 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,666 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 1
2023-08-01 11:29:16,666 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,666 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 1
2023-08-01 11:29:16,666 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 2
2023-08-01 11:29:16,666 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,667 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 2
2023-08-01 11:29:16,667 INFO    HandlerThread:22572 [system_monitor.py:finish():190] Stopping system monitor
2023-08-01 11:29:16,667 DEBUG   SystemMonitor:22572 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-08-01 11:29:16,668 DEBUG   SystemMonitor:22572 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-08-01 11:29:16,668 INFO    HandlerThread:22572 [interfaces.py:finish():202] Joined cpu monitor
2023-08-01 11:29:16,684 DEBUG   SystemMonitor:22572 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-08-01 11:29:16,684 INFO    HandlerThread:22572 [interfaces.py:finish():202] Joined disk monitor
2023-08-01 11:29:16,795 INFO    HandlerThread:22572 [interfaces.py:finish():202] Joined gpu monitor
2023-08-01 11:29:16,796 INFO    HandlerThread:22572 [interfaces.py:finish():202] Joined memory monitor
2023-08-01 11:29:16,796 INFO    HandlerThread:22572 [interfaces.py:finish():202] Joined network monitor
2023-08-01 11:29:16,797 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,797 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 2
2023-08-01 11:29:16,797 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 3
2023-08-01 11:29:16,797 DEBUG   SenderThread:22572 [sender.py:send():379] send: stats
2023-08-01 11:29:16,797 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,797 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 3
2023-08-01 11:29:16,798 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,798 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 3
2023-08-01 11:29:16,798 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 4
2023-08-01 11:29:16,799 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,799 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 4
2023-08-01 11:29:16,799 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,799 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 4
2023-08-01 11:29:16,799 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 5
2023-08-01 11:29:16,799 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,800 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 5
2023-08-01 11:29:16,800 DEBUG   SenderThread:22572 [sender.py:send():379] send: summary
2023-08-01 11:29:16,802 INFO    SenderThread:22572 [sender.py:_save_file():1376] saving file wandb-summary.json with policy end
2023-08-01 11:29:16,802 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,802 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 5
2023-08-01 11:29:16,803 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 6
2023-08-01 11:29:16,803 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:16,803 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 6
2023-08-01 11:29:16,804 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:16,804 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 6
2023-08-01 11:29:16,810 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:17,121 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 7
2023-08-01 11:29:17,121 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:17,121 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 7
2023-08-01 11:29:17,123 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:17,123 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 7
2023-08-01 11:29:17,530 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_modified():289] file/dir modified: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\wandb-summary.json
2023-08-01 11:29:17,531 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_modified():289] file/dir modified: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\config.yaml
2023-08-01 11:29:17,670 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:18,255 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 8
2023-08-01 11:29:18,257 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:18,258 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:18,259 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 8
2023-08-01 11:29:18,261 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:18,262 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 8
2023-08-01 11:29:18,262 INFO    SenderThread:22572 [job_builder.py:build():280] Attempting to build job artifact
2023-08-01 11:29:18,263 INFO    SenderThread:22572 [job_builder.py:build():296] run is notebook based run
2023-08-01 11:29:18,263 INFO    SenderThread:22572 [job_builder.py:_get_source_type():400] no source found
2023-08-01 11:29:18,264 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 9
2023-08-01 11:29:18,264 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:18,265 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 9
2023-08-01 11:29:18,266 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:18,267 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 9
2023-08-01 11:29:18,267 INFO    SenderThread:22572 [dir_watcher.py:finish():359] shutting down directory watcher
2023-08-01 11:29:18,534 INFO    Thread-16 :22572 [dir_watcher.py:_on_file_modified():289] file/dir modified: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\output.log
2023-08-01 11:29:18,536 INFO    SenderThread:22572 [dir_watcher.py:finish():389] scan: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files
2023-08-01 11:29:18,537 INFO    SenderThread:22572 [dir_watcher.py:finish():403] scan save: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\conda-environment.yaml conda-environment.yaml
2023-08-01 11:29:18,539 INFO    SenderThread:22572 [dir_watcher.py:finish():403] scan save: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\config.yaml config.yaml
2023-08-01 11:29:18,541 INFO    SenderThread:22572 [dir_watcher.py:finish():403] scan save: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\output.log output.log
2023-08-01 11:29:18,553 INFO    SenderThread:22572 [dir_watcher.py:finish():403] scan save: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\requirements.txt requirements.txt
2023-08-01 11:29:18,556 INFO    SenderThread:22572 [dir_watcher.py:finish():403] scan save: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\wandb-metadata.json wandb-metadata.json
2023-08-01 11:29:18,564 INFO    SenderThread:22572 [dir_watcher.py:finish():403] scan save: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\wandb-summary.json wandb-summary.json
2023-08-01 11:29:18,569 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 10
2023-08-01 11:29:18,572 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:18,575 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 10
2023-08-01 11:29:18,585 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:18,586 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 10
2023-08-01 11:29:18,586 INFO    SenderThread:22572 [file_pusher.py:finish():159] shutting down file pusher
2023-08-01 11:29:18,674 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:18,675 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:19,683 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:19,683 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:20,694 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:20,695 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:21,697 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:21,699 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:22,704 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:22,705 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:23,718 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:23,719 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:24,731 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:24,733 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:25,738 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:25,739 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:26,750 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:26,752 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:26,754 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:27,090 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-metadata.json?Expires=1690957755&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=JI9eecweVeOlw1saAJHVC4QDWuVKdZfCYLXaDI6HwjDGIz48qB70M3qc6bQ7m398cbYGjZ0%2FCIP8WDGSeDzjDHquRwlIbh0Fr0YFRBOsgWTXKdDivanhW5AobrGveztQ5vLaYfaW65Lk6kdt2peVW%2B6CgJXFIBPuwZe4QkBz40rRP4rii4lNd1tgq9rRT%2F5lEVSjakfVY%2FrIGBj4ss4HXyCDtqD1pbEdMweS%2Bb%2FHfqSS4gL8Jzaswe9GsbhfNMIYYjBnDvC0RLU0TcR5Q5xTa7DFcwfzDG0V7u%2FqKIbYao2AcV4EDxneF6MVHhMtEtCR4dXRusqxvQk7VmeKzlTbPQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-metadata.json?Expires=1690957755&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=JI9eecweVeOlw1saAJHVC4QDWuVKdZfCYLXaDI6HwjDGIz48qB70M3qc6bQ7m398cbYGjZ0%2FCIP8WDGSeDzjDHquRwlIbh0Fr0YFRBOsgWTXKdDivanhW5AobrGveztQ5vLaYfaW65Lk6kdt2peVW%2B6CgJXFIBPuwZe4QkBz40rRP4rii4lNd1tgq9rRT%2F5lEVSjakfVY%2FrIGBj4ss4HXyCDtqD1pbEdMweS%2Bb%2FHfqSS4gL8Jzaswe9GsbhfNMIYYjBnDvC0RLU0TcR5Q5xTa7DFcwfzDG0V7u%2FqKIbYao2AcV4EDxneF6MVHhMtEtCR4dXRusqxvQk7VmeKzlTbPQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD2C220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2023-08-01 11:29:27,091 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1090'}
2023-08-01 11:29:27,091 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:27,756 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:27,757 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:27,906 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/config.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=eSZeXbGR4%2FbDuK8wbuR1q6IYR842QwzfhSnFlsMf92XcNAnXQjKoUmKHPMRTEKClmLbqyR8nvQYTL2r1SUFzIqu0dzmG%2FuCQHPDFYOPKDhYtpjMOlJETghI%2F2GQZOFF82U78f7BRzU2qG2IfyHaD0A8bTktLmn9VSF0d6uWqQ%2F4aAgNVsZfNSqmiumOqeUJUp8zWRqt24b3yhxDXU6DsFrphhsXbfhgqXVgF4F8wNX%2FTegPIxixazo6LTC1fp%2Bsd51trZ0Q69niuDt%2FtEypRAiccclIUD3mFRWmLls1j8KTAoaI205UAXj06N%2FU5AfskrSuaTUovN7VZOPmhLB53jg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/config.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=eSZeXbGR4%2FbDuK8wbuR1q6IYR842QwzfhSnFlsMf92XcNAnXQjKoUmKHPMRTEKClmLbqyR8nvQYTL2r1SUFzIqu0dzmG%2FuCQHPDFYOPKDhYtpjMOlJETghI%2F2GQZOFF82U78f7BRzU2qG2IfyHaD0A8bTktLmn9VSF0d6uWqQ%2F4aAgNVsZfNSqmiumOqeUJUp8zWRqt24b3yhxDXU6DsFrphhsXbfhgqXVgF4F8wNX%2FTegPIxixazo6LTC1fp%2Bsd51trZ0Q69niuDt%2FtEypRAiccclIUD3mFRWmLls1j8KTAoaI205UAXj06N%2FU5AfskrSuaTUovN7VZOPmhLB53jg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBCDE2E0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:27,907 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '757'}
2023-08-01 11:29:27,908 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD2C280>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:27,908 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:27,910 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4900'}
2023-08-01 11:29:27,910 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:28,004 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-summary.json?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YEGICnmEjPVcAPDtHvukrz2MWwD%2BUYSkXZjEQf0vLGrFnqHrAxJdnWhQxv9YAKUkd4Cga%2FmFyPxFLedKyeUn6c0o38yucr45FHVZNRpyICuqATDdej5cBeqZQ1SArA%2BllG%2F77zqOhb8xC2sgEvRgIkhQO1sfoa4lYYu7%2B73j2UUMQV3WCr%2BkNm%2FYCrBRuKO4%2BNlgZVjKQjmZ3OOvWMoOBPMJq9%2B3jIV2oULzrNnIGo9klnxGp1XxiVuUwguTyXG1d5KCfuun9n8RpsYk7wMgt4vuEWjDdqc5EILFO5z5VpX6kuT%2BeCjybmG9VPtqdx4xXShrDsMCGPyRAf1ZiVEllA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-summary.json?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YEGICnmEjPVcAPDtHvukrz2MWwD%2BUYSkXZjEQf0vLGrFnqHrAxJdnWhQxv9YAKUkd4Cga%2FmFyPxFLedKyeUn6c0o38yucr45FHVZNRpyICuqATDdej5cBeqZQ1SArA%2BllG%2F77zqOhb8xC2sgEvRgIkhQO1sfoa4lYYu7%2B73j2UUMQV3WCr%2BkNm%2FYCrBRuKO4%2BNlgZVjKQjmZ3OOvWMoOBPMJq9%2B3jIV2oULzrNnIGo9klnxGp1XxiVuUwguTyXG1d5KCfuun9n8RpsYk7wMgt4vuEWjDdqc5EILFO5z5VpX6kuT%2BeCjybmG9VPtqdx4xXShrDsMCGPyRAf1ZiVEllA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD88FA0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:28,005 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2023-08-01 11:29:28,006 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:28,023 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/requirements.txt?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHANPTWSWoiHeqgp6n5HJyWBDSXHdIvUwnfwse6hbB7ryQSX3tjEBr6LS4awJX8652l%2FHv6tonHiJD0MuuBZKxZkhQk5MFC4Qbt%2Bc0GWH%2B9PNOopKRJmhZIVsbYhSNQzHyrXkgPmR%2BJgQssLNLVfWLDQ7oefPHsgiGjzxzLUXHKzKs1AMi%2FpwQXO9Q6Fwham8JnpIkG3X3nbcF9900HKc1s%2BvKqrZ4d8CbZ7bHh4wH9XlOonHzZkYctESfL4HP7qKXddB%2B3S9RMSFcU%2FSjSAQSRD7qbffJaCL7AsRflBGIT6ThCxWjtAbNoEmXLuTy0vl9%2BjcdxmV%2BRZFJ7Q%2BIwp%2FA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/requirements.txt?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHANPTWSWoiHeqgp6n5HJyWBDSXHdIvUwnfwse6hbB7ryQSX3tjEBr6LS4awJX8652l%2FHv6tonHiJD0MuuBZKxZkhQk5MFC4Qbt%2Bc0GWH%2B9PNOopKRJmhZIVsbYhSNQzHyrXkgPmR%2BJgQssLNLVfWLDQ7oefPHsgiGjzxzLUXHKzKs1AMi%2FpwQXO9Q6Fwham8JnpIkG3X3nbcF9900HKc1s%2BvKqrZ4d8CbZ7bHh4wH9XlOonHzZkYctESfL4HP7qKXddB%2B3S9RMSFcU%2FSjSAQSRD7qbffJaCL7AsRflBGIT6ThCxWjtAbNoEmXLuTy0vl9%2BjcdxmV%2BRZFJ7Q%2BIwp%2FA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD00340>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:28,025 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2735'}
2023-08-01 11:29:28,025 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:28,034 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/output.log?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FonuVn2TH02ygmVW3aq3mAed%2BqVlOLsM1SmG5998a6Vs0fT5LhkT%2BVpRlQ3K%2Bh3SpwpRGu8mGUOmw4GCH8F8%2FbxB5RnKNiPzX13lU%2B4oS2MvEf6eJ1HDXcpRVahpM91m6FI3XRSzao6l43GEsH0bQS%2B6PCHXQyp9xmIjkECUDmbm48Ro%2FVK7DfPUJg6Qg92bD%2FFW6zELSKykAw411T3dE2o2b3r%2BYtogOn522nAyilxRuxMDgb2bP7wCryq6JLGUEH3mv1kX5M%2FVA2zWNdQWWgFaBZ%2FkoEchcthAA%2FM4GBGWxjMRRXatEiJRO3dOh4qZPlMVndIptpkZj3Vtx0y8uQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/output.log?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FonuVn2TH02ygmVW3aq3mAed%2BqVlOLsM1SmG5998a6Vs0fT5LhkT%2BVpRlQ3K%2Bh3SpwpRGu8mGUOmw4GCH8F8%2FbxB5RnKNiPzX13lU%2B4oS2MvEf6eJ1HDXcpRVahpM91m6FI3XRSzao6l43GEsH0bQS%2B6PCHXQyp9xmIjkECUDmbm48Ro%2FVK7DfPUJg6Qg92bD%2FFW6zELSKykAw411T3dE2o2b3r%2BYtogOn522nAyilxRuxMDgb2bP7wCryq6JLGUEH3mv1kX5M%2FVA2zWNdQWWgFaBZ%2FkoEchcthAA%2FM4GBGWxjMRRXatEiJRO3dOh4qZPlMVndIptpkZj3Vtx0y8uQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD003D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:28,034 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1311'}
2023-08-01 11:29:28,034 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:28,264 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-metadata.json?Expires=1690957755&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=JI9eecweVeOlw1saAJHVC4QDWuVKdZfCYLXaDI6HwjDGIz48qB70M3qc6bQ7m398cbYGjZ0%2FCIP8WDGSeDzjDHquRwlIbh0Fr0YFRBOsgWTXKdDivanhW5AobrGveztQ5vLaYfaW65Lk6kdt2peVW%2B6CgJXFIBPuwZe4QkBz40rRP4rii4lNd1tgq9rRT%2F5lEVSjakfVY%2FrIGBj4ss4HXyCDtqD1pbEdMweS%2Bb%2FHfqSS4gL8Jzaswe9GsbhfNMIYYjBnDvC0RLU0TcR5Q5xTa7DFcwfzDG0V7u%2FqKIbYao2AcV4EDxneF6MVHhMtEtCR4dXRusqxvQk7VmeKzlTbPQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-metadata.json?Expires=1690957755&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=JI9eecweVeOlw1saAJHVC4QDWuVKdZfCYLXaDI6HwjDGIz48qB70M3qc6bQ7m398cbYGjZ0%2FCIP8WDGSeDzjDHquRwlIbh0Fr0YFRBOsgWTXKdDivanhW5AobrGveztQ5vLaYfaW65Lk6kdt2peVW%2B6CgJXFIBPuwZe4QkBz40rRP4rii4lNd1tgq9rRT%2F5lEVSjakfVY%2FrIGBj4ss4HXyCDtqD1pbEdMweS%2Bb%2FHfqSS4gL8Jzaswe9GsbhfNMIYYjBnDvC0RLU0TcR5Q5xTa7DFcwfzDG0V7u%2FqKIbYao2AcV4EDxneF6MVHhMtEtCR4dXRusqxvQk7VmeKzlTbPQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD00FA0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:28,264 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1090'}
2023-08-01 11:29:28,264 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:28,762 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:28,763 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:28,952 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBCD20A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:28,952 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4900'}
2023-08-01 11:29:28,952 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:28,952 INFO    wandb-upload_1:22572 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\Users\Pc\miniconda3\envs\tf\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C4EBCD20A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBCD20A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2285, in upload_file
    response = self._upload_file_session.put(
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBCD20A0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2314, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2285, in upload_file
    response = self._upload_file_session.put(
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "c:\Users\Pc\miniconda3\envs\tf\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-08-01 11:29:29,060 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-summary.json?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YEGICnmEjPVcAPDtHvukrz2MWwD%2BUYSkXZjEQf0vLGrFnqHrAxJdnWhQxv9YAKUkd4Cga%2FmFyPxFLedKyeUn6c0o38yucr45FHVZNRpyICuqATDdej5cBeqZQ1SArA%2BllG%2F77zqOhb8xC2sgEvRgIkhQO1sfoa4lYYu7%2B73j2UUMQV3WCr%2BkNm%2FYCrBRuKO4%2BNlgZVjKQjmZ3OOvWMoOBPMJq9%2B3jIV2oULzrNnIGo9klnxGp1XxiVuUwguTyXG1d5KCfuun9n8RpsYk7wMgt4vuEWjDdqc5EILFO5z5VpX6kuT%2BeCjybmG9VPtqdx4xXShrDsMCGPyRAf1ZiVEllA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-summary.json?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YEGICnmEjPVcAPDtHvukrz2MWwD%2BUYSkXZjEQf0vLGrFnqHrAxJdnWhQxv9YAKUkd4Cga%2FmFyPxFLedKyeUn6c0o38yucr45FHVZNRpyICuqATDdej5cBeqZQ1SArA%2BllG%2F77zqOhb8xC2sgEvRgIkhQO1sfoa4lYYu7%2B73j2UUMQV3WCr%2BkNm%2FYCrBRuKO4%2BNlgZVjKQjmZ3OOvWMoOBPMJq9%2B3jIV2oULzrNnIGo9klnxGp1XxiVuUwguTyXG1d5KCfuun9n8RpsYk7wMgt4vuEWjDdqc5EILFO5z5VpX6kuT%2BeCjybmG9VPtqdx4xXShrDsMCGPyRAf1ZiVEllA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD3B700>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:29,060 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2023-08-01 11:29:29,060 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:29,137 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/config.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=eSZeXbGR4%2FbDuK8wbuR1q6IYR842QwzfhSnFlsMf92XcNAnXQjKoUmKHPMRTEKClmLbqyR8nvQYTL2r1SUFzIqu0dzmG%2FuCQHPDFYOPKDhYtpjMOlJETghI%2F2GQZOFF82U78f7BRzU2qG2IfyHaD0A8bTktLmn9VSF0d6uWqQ%2F4aAgNVsZfNSqmiumOqeUJUp8zWRqt24b3yhxDXU6DsFrphhsXbfhgqXVgF4F8wNX%2FTegPIxixazo6LTC1fp%2Bsd51trZ0Q69niuDt%2FtEypRAiccclIUD3mFRWmLls1j8KTAoaI205UAXj06N%2FU5AfskrSuaTUovN7VZOPmhLB53jg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/config.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=eSZeXbGR4%2FbDuK8wbuR1q6IYR842QwzfhSnFlsMf92XcNAnXQjKoUmKHPMRTEKClmLbqyR8nvQYTL2r1SUFzIqu0dzmG%2FuCQHPDFYOPKDhYtpjMOlJETghI%2F2GQZOFF82U78f7BRzU2qG2IfyHaD0A8bTktLmn9VSF0d6uWqQ%2F4aAgNVsZfNSqmiumOqeUJUp8zWRqt24b3yhxDXU6DsFrphhsXbfhgqXVgF4F8wNX%2FTegPIxixazo6LTC1fp%2Bsd51trZ0Q69niuDt%2FtEypRAiccclIUD3mFRWmLls1j8KTAoaI205UAXj06N%2FU5AfskrSuaTUovN7VZOPmhLB53jg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD3B160>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:29,138 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '757'}
2023-08-01 11:29:29,138 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:29,151 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/requirements.txt?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHANPTWSWoiHeqgp6n5HJyWBDSXHdIvUwnfwse6hbB7ryQSX3tjEBr6LS4awJX8652l%2FHv6tonHiJD0MuuBZKxZkhQk5MFC4Qbt%2Bc0GWH%2B9PNOopKRJmhZIVsbYhSNQzHyrXkgPmR%2BJgQssLNLVfWLDQ7oefPHsgiGjzxzLUXHKzKs1AMi%2FpwQXO9Q6Fwham8JnpIkG3X3nbcF9900HKc1s%2BvKqrZ4d8CbZ7bHh4wH9XlOonHzZkYctESfL4HP7qKXddB%2B3S9RMSFcU%2FSjSAQSRD7qbffJaCL7AsRflBGIT6ThCxWjtAbNoEmXLuTy0vl9%2BjcdxmV%2BRZFJ7Q%2BIwp%2FA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/requirements.txt?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHANPTWSWoiHeqgp6n5HJyWBDSXHdIvUwnfwse6hbB7ryQSX3tjEBr6LS4awJX8652l%2FHv6tonHiJD0MuuBZKxZkhQk5MFC4Qbt%2Bc0GWH%2B9PNOopKRJmhZIVsbYhSNQzHyrXkgPmR%2BJgQssLNLVfWLDQ7oefPHsgiGjzxzLUXHKzKs1AMi%2FpwQXO9Q6Fwham8JnpIkG3X3nbcF9900HKc1s%2BvKqrZ4d8CbZ7bHh4wH9XlOonHzZkYctESfL4HP7qKXddB%2B3S9RMSFcU%2FSjSAQSRD7qbffJaCL7AsRflBGIT6ThCxWjtAbNoEmXLuTy0vl9%2BjcdxmV%2BRZFJ7Q%2BIwp%2FA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD3BF10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:29,151 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2735'}
2023-08-01 11:29:29,151 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:29,268 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/output.log?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FonuVn2TH02ygmVW3aq3mAed%2BqVlOLsM1SmG5998a6Vs0fT5LhkT%2BVpRlQ3K%2Bh3SpwpRGu8mGUOmw4GCH8F8%2FbxB5RnKNiPzX13lU%2B4oS2MvEf6eJ1HDXcpRVahpM91m6FI3XRSzao6l43GEsH0bQS%2B6PCHXQyp9xmIjkECUDmbm48Ro%2FVK7DfPUJg6Qg92bD%2FFW6zELSKykAw411T3dE2o2b3r%2BYtogOn522nAyilxRuxMDgb2bP7wCryq6JLGUEH3mv1kX5M%2FVA2zWNdQWWgFaBZ%2FkoEchcthAA%2FM4GBGWxjMRRXatEiJRO3dOh4qZPlMVndIptpkZj3Vtx0y8uQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/output.log?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FonuVn2TH02ygmVW3aq3mAed%2BqVlOLsM1SmG5998a6Vs0fT5LhkT%2BVpRlQ3K%2Bh3SpwpRGu8mGUOmw4GCH8F8%2FbxB5RnKNiPzX13lU%2B4oS2MvEf6eJ1HDXcpRVahpM91m6FI3XRSzao6l43GEsH0bQS%2B6PCHXQyp9xmIjkECUDmbm48Ro%2FVK7DfPUJg6Qg92bD%2FFW6zELSKykAw411T3dE2o2b3r%2BYtogOn522nAyilxRuxMDgb2bP7wCryq6JLGUEH3mv1kX5M%2FVA2zWNdQWWgFaBZ%2FkoEchcthAA%2FM4GBGWxjMRRXatEiJRO3dOh4qZPlMVndIptpkZj3Vtx0y8uQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBCD27F0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:29,269 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1311'}
2023-08-01 11:29:29,269 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:29,767 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:29,767 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:30,377 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-metadata.json?Expires=1690957755&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=JI9eecweVeOlw1saAJHVC4QDWuVKdZfCYLXaDI6HwjDGIz48qB70M3qc6bQ7m398cbYGjZ0%2FCIP8WDGSeDzjDHquRwlIbh0Fr0YFRBOsgWTXKdDivanhW5AobrGveztQ5vLaYfaW65Lk6kdt2peVW%2B6CgJXFIBPuwZe4QkBz40rRP4rii4lNd1tgq9rRT%2F5lEVSjakfVY%2FrIGBj4ss4HXyCDtqD1pbEdMweS%2Bb%2FHfqSS4gL8Jzaswe9GsbhfNMIYYjBnDvC0RLU0TcR5Q5xTa7DFcwfzDG0V7u%2FqKIbYao2AcV4EDxneF6MVHhMtEtCR4dXRusqxvQk7VmeKzlTbPQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-metadata.json?Expires=1690957755&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=JI9eecweVeOlw1saAJHVC4QDWuVKdZfCYLXaDI6HwjDGIz48qB70M3qc6bQ7m398cbYGjZ0%2FCIP8WDGSeDzjDHquRwlIbh0Fr0YFRBOsgWTXKdDivanhW5AobrGveztQ5vLaYfaW65Lk6kdt2peVW%2B6CgJXFIBPuwZe4QkBz40rRP4rii4lNd1tgq9rRT%2F5lEVSjakfVY%2FrIGBj4ss4HXyCDtqD1pbEdMweS%2Bb%2FHfqSS4gL8Jzaswe9GsbhfNMIYYjBnDvC0RLU0TcR5Q5xTa7DFcwfzDG0V7u%2FqKIbYao2AcV4EDxneF6MVHhMtEtCR4dXRusqxvQk7VmeKzlTbPQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD88130>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:30,377 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1090'}
2023-08-01 11:29:30,377 ERROR   wandb-upload_0:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:30,775 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:30,776 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:31,122 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-summary.json?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YEGICnmEjPVcAPDtHvukrz2MWwD%2BUYSkXZjEQf0vLGrFnqHrAxJdnWhQxv9YAKUkd4Cga%2FmFyPxFLedKyeUn6c0o38yucr45FHVZNRpyICuqATDdej5cBeqZQ1SArA%2BllG%2F77zqOhb8xC2sgEvRgIkhQO1sfoa4lYYu7%2B73j2UUMQV3WCr%2BkNm%2FYCrBRuKO4%2BNlgZVjKQjmZ3OOvWMoOBPMJq9%2B3jIV2oULzrNnIGo9klnxGp1XxiVuUwguTyXG1d5KCfuun9n8RpsYk7wMgt4vuEWjDdqc5EILFO5z5VpX6kuT%2BeCjybmG9VPtqdx4xXShrDsMCGPyRAf1ZiVEllA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/wandb-summary.json?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=YEGICnmEjPVcAPDtHvukrz2MWwD%2BUYSkXZjEQf0vLGrFnqHrAxJdnWhQxv9YAKUkd4Cga%2FmFyPxFLedKyeUn6c0o38yucr45FHVZNRpyICuqATDdej5cBeqZQ1SArA%2BllG%2F77zqOhb8xC2sgEvRgIkhQO1sfoa4lYYu7%2B73j2UUMQV3WCr%2BkNm%2FYCrBRuKO4%2BNlgZVjKQjmZ3OOvWMoOBPMJq9%2B3jIV2oULzrNnIGo9klnxGp1XxiVuUwguTyXG1d5KCfuun9n8RpsYk7wMgt4vuEWjDdqc5EILFO5z5VpX6kuT%2BeCjybmG9VPtqdx4xXShrDsMCGPyRAf1ZiVEllA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD00A30>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:31,123 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '27'}
2023-08-01 11:29:31,123 ERROR   wandb-upload_5:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:31,250 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/conda-environment.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=DShJMEiSqY9V2sylUkSdgJFMpaMsrPKAGMxFC5XSpRev7UjU95uzuYlBjrvtWFPonm87xeh4kAFY2m%2Brrh6jh7B40EjLSHP8bwSX9ZAiDdfyK9Cf6xURAl5KU7o2GKfL3asPdsbiyjpqnoZrV4a%2BepON5xRLdiEyb6tZEt%2FUj89pVC3Az266bAF24qsL5rPKqFDNwl5BOAKUWhDRRgWmpvHUFPeKp8AJH%2FRQVbdWpS3PiwZsxFoy6S8KTxChSgBA0%2BJpcKTLWu97sLjbS8zH1eOhsDwVnuN76NAU7n2hekI%2Byn1HOHCthDBdH2%2FDuND%2FEIXebKZXGKuYPdQNJRGicw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD000D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:31,251 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '4900'}
2023-08-01 11:29:31,251 ERROR   wandb-upload_1:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:31,383 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/requirements.txt?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHANPTWSWoiHeqgp6n5HJyWBDSXHdIvUwnfwse6hbB7ryQSX3tjEBr6LS4awJX8652l%2FHv6tonHiJD0MuuBZKxZkhQk5MFC4Qbt%2Bc0GWH%2B9PNOopKRJmhZIVsbYhSNQzHyrXkgPmR%2BJgQssLNLVfWLDQ7oefPHsgiGjzxzLUXHKzKs1AMi%2FpwQXO9Q6Fwham8JnpIkG3X3nbcF9900HKc1s%2BvKqrZ4d8CbZ7bHh4wH9XlOonHzZkYctESfL4HP7qKXddB%2B3S9RMSFcU%2FSjSAQSRD7qbffJaCL7AsRflBGIT6ThCxWjtAbNoEmXLuTy0vl9%2BjcdxmV%2BRZFJ7Q%2BIwp%2FA%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/requirements.txt?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHANPTWSWoiHeqgp6n5HJyWBDSXHdIvUwnfwse6hbB7ryQSX3tjEBr6LS4awJX8652l%2FHv6tonHiJD0MuuBZKxZkhQk5MFC4Qbt%2Bc0GWH%2B9PNOopKRJmhZIVsbYhSNQzHyrXkgPmR%2BJgQssLNLVfWLDQ7oefPHsgiGjzxzLUXHKzKs1AMi%2FpwQXO9Q6Fwham8JnpIkG3X3nbcF9900HKc1s%2BvKqrZ4d8CbZ7bHh4wH9XlOonHzZkYctESfL4HP7qKXddB%2B3S9RMSFcU%2FSjSAQSRD7qbffJaCL7AsRflBGIT6ThCxWjtAbNoEmXLuTy0vl9%2BjcdxmV%2BRZFJ7Q%2BIwp%2FA%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBDA6C10>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:31,383 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2735'}
2023-08-01 11:29:31,383 ERROR   wandb-upload_4:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:31,492 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/config.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=eSZeXbGR4%2FbDuK8wbuR1q6IYR842QwzfhSnFlsMf92XcNAnXQjKoUmKHPMRTEKClmLbqyR8nvQYTL2r1SUFzIqu0dzmG%2FuCQHPDFYOPKDhYtpjMOlJETghI%2F2GQZOFF82U78f7BRzU2qG2IfyHaD0A8bTktLmn9VSF0d6uWqQ%2F4aAgNVsZfNSqmiumOqeUJUp8zWRqt24b3yhxDXU6DsFrphhsXbfhgqXVgF4F8wNX%2FTegPIxixazo6LTC1fp%2Bsd51trZ0Q69niuDt%2FtEypRAiccclIUD3mFRWmLls1j8KTAoaI205UAXj06N%2FU5AfskrSuaTUovN7VZOPmhLB53jg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/config.yaml?Expires=1690957758&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=eSZeXbGR4%2FbDuK8wbuR1q6IYR842QwzfhSnFlsMf92XcNAnXQjKoUmKHPMRTEKClmLbqyR8nvQYTL2r1SUFzIqu0dzmG%2FuCQHPDFYOPKDhYtpjMOlJETghI%2F2GQZOFF82U78f7BRzU2qG2IfyHaD0A8bTktLmn9VSF0d6uWqQ%2F4aAgNVsZfNSqmiumOqeUJUp8zWRqt24b3yhxDXU6DsFrphhsXbfhgqXVgF4F8wNX%2FTegPIxixazo6LTC1fp%2Bsd51trZ0Q69niuDt%2FtEypRAiccclIUD3mFRWmLls1j8KTAoaI205UAXj06N%2FU5AfskrSuaTUovN7VZOPmhLB53jg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD2CD30>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:31,492 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '757'}
2023-08-01 11:29:31,492 ERROR   wandb-upload_2:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:31,543 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2290] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/output.log?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FonuVn2TH02ygmVW3aq3mAed%2BqVlOLsM1SmG5998a6Vs0fT5LhkT%2BVpRlQ3K%2Bh3SpwpRGu8mGUOmw4GCH8F8%2FbxB5RnKNiPzX13lU%2B4oS2MvEf6eJ1HDXcpRVahpM91m6FI3XRSzao6l43GEsH0bQS%2B6PCHXQyp9xmIjkECUDmbm48Ro%2FVK7DfPUJg6Qg92bD%2FFW6zELSKykAw411T3dE2o2b3r%2BYtogOn522nAyilxRuxMDgb2bP7wCryq6JLGUEH3mv1kX5M%2FVA2zWNdQWWgFaBZ%2FkoEchcthAA%2FM4GBGWxjMRRXatEiJRO3dOh4qZPlMVndIptpkZj3Vtx0y8uQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/ahsanbilal/uncategorized/yma4yd7g/output.log?Expires=1690957768&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=FonuVn2TH02ygmVW3aq3mAed%2BqVlOLsM1SmG5998a6Vs0fT5LhkT%2BVpRlQ3K%2Bh3SpwpRGu8mGUOmw4GCH8F8%2FbxB5RnKNiPzX13lU%2B4oS2MvEf6eJ1HDXcpRVahpM91m6FI3XRSzao6l43GEsH0bQS%2B6PCHXQyp9xmIjkECUDmbm48Ro%2FVK7DfPUJg6Qg92bD%2FFW6zELSKykAw411T3dE2o2b3r%2BYtogOn522nAyilxRuxMDgb2bP7wCryq6JLGUEH3mv1kX5M%2FVA2zWNdQWWgFaBZ%2FkoEchcthAA%2FM4GBGWxjMRRXatEiJRO3dOh4qZPlMVndIptpkZj3Vtx0y8uQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C4EBD2C9D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))
2023-08-01 11:29:31,543 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2292] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1311'}
2023-08-01 11:29:31,543 ERROR   wandb-upload_3:22572 [internal_api.py:upload_file():2294] upload_file response body: 
2023-08-01 11:29:31,781 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:31,781 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:31,781 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:32,798 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:32,799 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:33,810 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:33,810 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:34,824 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:34,825 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:35,837 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:35,837 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:36,845 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: status_report
2023-08-01 11:29:36,845 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:36,846 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:36,875 INFO    wandb-upload_0:22572 [upload_job.py:push():131] Uploaded file C:\Users\Pc\AppData\Local\Temp\tmpggdso85hwandb\vz5f2nua-wandb-metadata.json
2023-08-01 11:29:37,057 INFO    wandb-upload_5:22572 [upload_job.py:push():131] Uploaded file d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\wandb-summary.json
2023-08-01 11:29:37,550 INFO    wandb-upload_1:22572 [upload_job.py:push():131] Uploaded file d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\conda-environment.yaml
2023-08-01 11:29:37,772 INFO    wandb-upload_4:22572 [upload_job.py:push():131] Uploaded file d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\requirements.txt
2023-08-01 11:29:37,853 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:37,854 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:38,057 INFO    wandb-upload_2:22572 [upload_job.py:push():131] Uploaded file d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\config.yaml
2023-08-01 11:29:38,081 INFO    wandb-upload_3:22572 [upload_job.py:push():131] Uploaded file d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\files\output.log
2023-08-01 11:29:38,287 INFO    Thread-15 :22572 [sender.py:transition_state():612] send defer: 11
2023-08-01 11:29:38,288 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:38,288 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 11
2023-08-01 11:29:38,290 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:38,290 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 11
2023-08-01 11:29:38,291 INFO    SenderThread:22572 [file_pusher.py:join():164] waiting for file pusher
2023-08-01 11:29:38,291 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 12
2023-08-01 11:29:38,293 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:38,294 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 12
2023-08-01 11:29:38,295 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:38,295 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 12
2023-08-01 11:29:38,633 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 13
2023-08-01 11:29:38,634 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:38,634 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 13
2023-08-01 11:29:38,634 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:38,634 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 13
2023-08-01 11:29:38,634 INFO    SenderThread:22572 [sender.py:transition_state():612] send defer: 14
2023-08-01 11:29:38,635 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: defer
2023-08-01 11:29:38,635 DEBUG   SenderThread:22572 [sender.py:send():379] send: final
2023-08-01 11:29:38,635 INFO    HandlerThread:22572 [handler.py:handle_request_defer():170] handle defer: 14
2023-08-01 11:29:38,635 DEBUG   SenderThread:22572 [sender.py:send():379] send: footer
2023-08-01 11:29:38,635 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: defer
2023-08-01 11:29:38,636 INFO    SenderThread:22572 [sender.py:send_request_defer():608] handle sender defer: 14
2023-08-01 11:29:38,639 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: poll_exit
2023-08-01 11:29:38,639 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: server_info
2023-08-01 11:29:38,640 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: get_summary
2023-08-01 11:29:38,640 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: sampled_history
2023-08-01 11:29:38,641 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: poll_exit
2023-08-01 11:29:38,642 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: job_info
2023-08-01 11:29:38,645 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: server_info
2023-08-01 11:29:39,225 DEBUG   SenderThread:22572 [sender.py:send_request():406] send_request: job_info
2023-08-01 11:29:39,228 DEBUG   HandlerThread:22572 [handler.py:handle_request():144] handle_request: shutdown
2023-08-01 11:29:39,228 INFO    HandlerThread:22572 [handler.py:finish():857] shutting down handler
2023-08-01 11:29:39,661 INFO    WriterThread:22572 [datastore.py:close():294] close: d:\Tensorflow Basics\Car Price Prediction\wandb\run-20230801_112900-yma4yd7g\run-yma4yd7g.wandb
2023-08-01 11:29:40,234 INFO    SenderThread:22572 [sender.py:finish():1552] shutting down sender
2023-08-01 11:29:40,235 INFO    SenderThread:22572 [file_pusher.py:finish():159] shutting down file pusher
2023-08-01 11:29:40,235 INFO    SenderThread:22572 [file_pusher.py:join():164] waiting for file pusher
